[package]
name = "modelforge-clinical-mcp-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
http.workspace = true
modelforge-clinical-mcp-core = { path = "../gateway-core" }
rmcp.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
